### ISSUE TITLE
[Spike] Try out Spotless; outcome: Do include Spotless in the project

### ISSUE THREAD

**Issue by jwlibby** [binkley/modern-java-practices#489]
Try out Spotless and see what you think.  When evaluating refer to the questions in #462 and upon completion add your pros and cons for this plugin as a comment to the aforementioned story.  Plugin link: [Spotless](https://github.com/diffplug/spotless).

Considerations for implementation cards:
- Gradle: easy
- Maven: ~~lots of challenges, dependencies: Plexus, SLF4J, Kotlin, Eclipse; the plugin dependency wants Sonatype rather than Maven Central~~ also easy.  The challenges and dependencies issues mentioned were because I had incorrectly added the plugin as a dependency, not as a plugin

Related: #534 for epic on dependency management.

**Comment by jwlibby** [comment]
spike can be found in spotless-spike branch

**Comment by binkley** [comment]
Note: the `spotless-spike` branch has a mistake in using Spotless as a dependency rather than a plugin.

**Comment by binkley** [comment]
@jwlibby The only feedback I have on the writing is this:
```markdown
* [Spotless](https://github.com/diffplug/spotless) &mdash; Focus on Google style guides for Java.
```
I'm unsure what style to suggest here. For example, I noticed the Google style includes the "AOSP" variant that uses 4-space indentation rather than Google's odd 2-space indentation. Palantir is also an interesting choice.

So perhaps soften the language to not offer a recommendation on style choice.
